import js from '@eslint/js';

const browserGlobals = {
  document: 'readonly',
  window: 'readonly',
  navigator: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  fetch: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  AbortController: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  requestIdleCallback: 'readonly',
  cancelIdleCallback: 'readonly',
  queueMicrotask: 'readonly',
  console: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  Math: 'readonly',
  JSON: 'readonly',
  Date: 'readonly',
  RegExp: 'readonly',
  Map: 'readonly',
  Set: 'readonly',
  Promise: 'readonly',
  BigInt: 'readonly',
  Array: 'readonly',
  Object: 'readonly',
  String: 'readonly',
  Number: 'readonly',
  Boolean: 'readonly',
  Symbol: 'readonly',
  WeakMap: 'readonly',
  WeakSet: 'readonly',
  Proxy: 'readonly',
  Reflect: 'readonly',
  Intl: 'readonly',
  structuredClone: 'readonly',
  crypto: 'readonly',
  performance: 'readonly',
  location: 'readonly',
  history: 'readonly',
  matchMedia: 'readonly',
  CustomEvent: 'readonly',
  Event: 'readonly',
  EventTarget: 'readonly',
  MutationObserver: 'readonly',
  ResizeObserver: 'readonly',
  IntersectionObserver: 'readonly',
  Element: 'readonly',
  Node: 'readonly',
  NodeFilter: 'readonly',
  Image: 'readonly',
  FileReader: 'readonly',
  HTMLElement: 'readonly',
  HTMLImageElement: 'readonly',
  HTMLVideoElement: 'readonly',
  HTMLAudioElement: 'readonly',
  HTMLInputElement: 'readonly',
  HTMLTextAreaElement: 'readonly',
  HTMLIFrameElement: 'readonly',
  MessageEvent: 'readonly',
  EventSource: 'readonly',
  CSS: 'readonly',
  getComputedStyle: 'readonly'
};

const nodeGlobals = {
  process: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  console: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  setImmediate: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  AbortController: 'readonly',
  fetch: 'readonly',
  Math: 'readonly',
  JSON: 'readonly',
  Date: 'readonly',
  RegExp: 'readonly',
  Map: 'readonly',
  Set: 'readonly',
  Promise: 'readonly',
  BigInt: 'readonly',
  Array: 'readonly',
  Object: 'readonly',
  String: 'readonly',
  Number: 'readonly',
  Boolean: 'readonly',
  Symbol: 'readonly',
  structuredClone: 'readonly',
  performance: 'readonly'
};

const appGlobals = {
  escapeHtml: 'readonly',
  escapeAttr: 'readonly',
  clone: 'readonly',
  toast: 'readonly',
  api: 'readonly',
  state: 'readonly',
  apiRequestWithRetry: 'readonly',
  handleExpiredSession: 'readonly',
  showAppConfirm: 'readonly',
  setView: 'readonly',
  refreshConfig: 'readonly',
  loadStudioTemplate: 'readonly',
  renderDrafts: 'readonly',
  makeId: 'readonly',
  readLocalJson: 'readonly',
  savePatch: 'readonly',
  currentStudioTemplate: 'readonly',
  renderStudioLimits: 'readonly',
  saveStudioDesign: 'readonly',
  studioChannelMeta: 'readonly',
  isForumPostTarget: 'readonly',
  forumPostTitleFromTemplate: 'readonly',
  selectedForumPostTagIds: 'readonly',
  normalizeOutsideImageAttachment: 'readonly',
  makeStudioTemplateStorageSafe: 'readonly',
  renderStudioChannels: 'readonly',
  updatePreview: 'readonly',
  activeCatalog: 'readonly',
  moduleEnabled: 'readonly',
  getNormalizedFeatureById: 'readonly',
  setText: 'readonly',
  tempVoiceUi: 'readonly',
  bindId: 'readonly',
  openMessageEmojiPicker: 'readonly',
  activeView: 'readonly',
  openCommandPalette: 'readonly',
  renderCommandPalette: 'readonly',
  activateCommand: 'readonly',
  normalizeModuleConfigIds: 'readonly',
  FHCCAppEditor: 'readonly',
  FHCCModuleConfigInputs: 'readonly',
  FHCCCountingPanel: 'readonly',
  FHCCInactiveReminderPanel: 'readonly',
  FHCCLevelsPanel: 'readonly',
  FHCCStudioComponents: 'readonly',
  FHCCEconomyPanelStudio: 'readonly',
  FHCCJsonImport: 'readonly',
  lockAvatarHtml: 'readonly',
  formatLockRemaining: 'readonly',
  botUpdatesStudioTemplate: 'readonly',
  botUpdatesOverview: 'readonly',
  roleSaverOverview: 'readonly',
  refreshRoleSaverStatus: 'readonly',
  levelsPreviewTemplate: 'readonly',
  levelUpPreviewTemplate: 'readonly',
  levelUpInfoPreviewTemplate: 'readonly',
  botUpdatesPreviewTemplate: 'readonly',
  countingPreviewTemplate: 'readonly',
  countingDmPreviewTemplate: 'readonly',
  inactiveReminderPreviewTemplate: 'readonly',
  saveLevelsStudioTemplate: 'readonly',
  saveLevelUpStudioTemplate: 'readonly',
  saveLevelUpInfoStudioTemplate: 'readonly',
  saveCountingStudioTemplate: 'readonly',
  saveCountingDmStudioTemplate: 'readonly',
  saveInactiveReminderStudioTemplate: 'readonly',
  levelsStudioTemplate: 'readonly',
  levelUpStudioTemplate: 'readonly',
  levelUpInfoStudioTemplate: 'readonly',
  countingDmStudioTemplate: 'readonly'
};

export default [
  js.configs.recommended,
  {
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-fallthrough': 'warn',
      'no-shadow': 'warn',
      'eqeqeq': ['warn', 'always', { null: 'ignore' }],
      'prefer-const': 'warn',
      'no-var': 'warn',
      'no-useless-assignment': 'warn'
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module'
    }
  },
  {
    files: ['src/**/*.js'],
    languageOptions: {
      globals: nodeGlobals
    }
  },
  {
    files: ['desktop/renderer/**/*.js'],
    languageOptions: {
      globals: {
        ...browserGlobals,
        ...appGlobals
      }
    }
  },
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'build/**',
      'desktop/build/**',
      'data/**',
      'runtime/**',
      'docs/**',
      'scripts/**',
      'public/**',
      'tests/**',
      '**/*.cjs',
      '**/*.html'
    ]
  }
];
